
export const DATA_UPDATE = 'DATA_UPDATE';
export const REPOS_DATA_UPDATE = 'REPOS_DATA_UPDATE';
export const PAGES_DATA_UPDATE = 'PAGES_DATA_UPDATE';
export const PAGINATION_UPDATE = 'PAGINATION_UPDATE';
export const SEARCH_UPDATE = 'SEARCH_UPDATE';
export const LOADING = 'LOADING';
export const UPDATE_ERRORS = 'UPDATE_ERRORS';
